### ISSUE TITLE
Roadmap wrong on home page

### ISSUE THREAD

**Issue by henrjk** [opendevstack/opendevstack.github.io#115]
On page http://www.opendevstack.org/index.html:

Roadmap
June 2019 - release 1.1
October 2019 - release 2.0
Following: Release of continuously advanced versions

The 2.0 version is planned for December I think and 1.2 is missing.

**Comment by tbugfinder** [comment]
and 3.0 is in development.
As this is an entrypoint to ODS, fixing it should have higher priority.
