### ISSUE TITLE
Add Troubleshooting section

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/opendevstack.github.io#12]
Add a chapter to getting started with errors that can happen and what to do in this cases.

**Comment by slechte** [comment]
I already added a file "troubleshooting.md" for this purpose.
But it is currently not referenced in the getting started guide and should be included.

**Comment by clemensutschig** [comment]
@slechte  - sebastian - do you work those documentation / getting started topics now .. ? just asking - so I don't get started.
