### ISSUE TITLE
Page Not Found - local-install.html

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/opendevstack.github.io#123]
Clicking on `Installation Guide` or on `Getting started - installation` refers to the url `https://www.opendevstack.org/ods-documentation/common/latest/getting-started/local-install.html` which does not exist.

![11-11-_2019_08-05-57](https://user-images.githubusercontent.com/17799657/68567920-7d102800-045a-11ea-8171-4238387d9989.gif)

**Comment by stefanlack** [comment]
@SimonGolms  thanks for creating this issue. I will correct the links.
In the meantime you may find the content of the local installation guide by navigation via Documentation --> Guides and Tutorials --> Local Install Guide --< Overview
