### ISSUE TITLE
Browser display broken

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/opendevstack.github.io#19]
The page looks really broken from me on Mac Chrome/Safari ...

![screen shot 2018-08-16 at 09 22 46](https://user-images.githubusercontent.com/215455/44194365-10fb2300-a136-11e8-82f1-0448e49e7861.png)

**Comment by tjaeschke** [comment]
Should be fixed in #18

**Comment by tjaeschke** [comment]
In the last merge the divs for the sonarqube logos haven't been closed correctly.

**Comment by tjaeschke** [comment]
After merge the page isn't broken anymore, but the sonatype logo is stretched. This will be tarcked in a new issue
