### ISSUE TITLE
Add missing technologies & roadmap to Main page

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/opendevstack.github.io#7]
Nexus sonarqube owasp

**Comment by michaelsauter** [comment]
Is this done?

**Comment by patschart** [comment]
Roadmap now reads: 

- September:  Realease V1.0
- Following: Release of continuously advanced versions
If you are interested in OpenDevStack, as a user or contributor, please contact us.

Nexus Sonarqube logo has been added. 
http://www.opendevstack.org/

**Comment by clemensutschig** [comment]
Fixed- tech and Roadmap available
