### ISSUE TITLE
Document which changes are accepted in which branch

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/opendevstack.github.io#73]
The contribution guide (https://github.com/opendevstack/opendevstack.github.io/blob/master/doc/development-guide.md) contains a section at the end regarding acceptance criteria of PRs. We need to add something regarding release management. Basically, branches from which patch versions are created (e.g. `1.0.x`) will only accept PRs which are bugfixes. PRs containing features will have to go into master. As a consequence:
* users are more likely to update regularly in order to get new features
* reduced amount of maintenance on our part
* minimal effort required to update between patch versions (because ideally nothing needs to be rebuilt)

@clemensutschig As discussed with you. @stitakis @rattermeyer @tjaeschke Agreed?

**Comment by clemensutschig** [comment]
@michaelsauter  - yes. if the info is there - feel free to close

**Comment by stitakis** [comment]
sounds good to me

**Comment by michaelsauter** [comment]
Actually, reading the guide it **is** documented :) Forgot that. Closing.
