### ISSUE TITLE
need documentation / getting started for new users of opendevstack

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/opendevstack.github.io#79]
- overall: where do I find all this information & how do I work with github ...
-- support issues
- from code to running image, how does the whole thing work together
-- branch model (what makes an image go where?)
-- continuous delivery (webhooks) 
-- account mgmt (which accounts)
- what does each quickstarter do
- what are the files generated - and what are they used for (in the later (jenkins) stages)
- most common usecases
-- have an existing dockerFile
-- binary war
-- build a new application

**Comment by michaelsauter** [comment]
So maybe we can start by collecting what information we already have on those topics, and then we can figure out a) what we still need to provide and b) where the information should live.

I know that we have documentation on the branch/environment mapping in https://github.com/opendevstack/ods-jenkins-shared-library/blob/v1.0.1/README.md. In that readme, there is also documentation on how to extend/adjust the `Jenkinsfile`.

**Comment by gerardcl** [comment]
shouldn't we align this with the possible antora's implementation?

**Comment by michaelsauter** [comment]
@rattermeyer I think yes, this should be aligned?

**Comment by clemensutschig** [comment]
@rattermeyer  - what's the status of this

**Comment by clemensutschig** [comment]
start from a the provision app - pick a quickstarter - and go from there

1. technologies used (with links to more doc ... )

1. from push / clone - commit / push - to environment image / deploy config (shared library)
1.1 webhooks generated / repositories -> via provision application (@clemensutschig  - done - PR open)

1. we need doc for each quickstarter on (template: opendevstack/ods-project-quickstarters#151)
1.1.1 spring boot - sebastian
1.1.1 fe-angular - balram
1.1.1 node-express - akhil
1.1.1 ionic - janet
1.1.1 dl_ml & python - hugo
1.1.1 react - maria
1.1.1 rshiny / jupyther - stefan
1.1.1 docker - plain 
1.1.1 scala - jan
1.1.1 cypress - christian s

1.1 what it does and when you should use it
1.1 what is in and what's generated
1.1 jenkins stages (if different from "plain") 

1. how to manage your openshift project / secrets / - link to OC doc?!

1. How do I ...

**Comment by nadjaleyendecker** [comment]
Lot of content was added in GitHub (e.g. for quickstarters) as well as getting started overview at http://www.opendevstack.org/doc/overview.html
Fine for me, covers my requirements - from my point of view, issue can be closed.

**Comment by rattermeyer** [comment]
antora PRs are opened. We have made it much easier to setup OpenDevStack (locally) and are on the way to generally improve documentation.
