### ISSUE TITLE
Minishift configuration in documentation suggests manual changes

### ISSUE THREAD

**Issue by gbraad** [opendevstack/opendevstack.github.io#83]
As can be seen in: https://github.com/opendevstack/opendevstack.github.io/blob/b1bcf874f3e532f804ec56d42dfce96f67a2428c/doc/getting-started.md#configure-minishift you modify `config.json` directly. It is suggested to use:

```
$ minishift config set [key] [value]
```

**Comment by tjaeschke** [comment]
Hi, there is a refactoring in progress with a documentation rework, where this will be changed.

**Comment by gbraad** [comment]
OK, just wondering as a malformed configuration file prevents minishift from starting.

**Comment by tjaeschke** [comment]
obsolete with infrastructure refactoring
